kind: Deployment
apiVersion: apps/v1
metadata:
  name: ingress-dly
  namespace: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
     app: note

  template:
    metadata:
      name: ingress-pod
      labels:
        app: note

    spec:
      containers:
        - name: ingress-container
          image: sumansahudockerhub/note-app
          ports:
           - containerPort: 8000
