kind: CronJob
apiVersion: batch/v1
metadata:
  name: demo-cronjob
  namespace: nginx
spec:
  schedule: "* * * * *"
  jobTemplate:
    spec:
     template:
      metadata:
        name: pod
        labels:
          app: minute-backup
      spec:
        containers:
          - name: cronjob-demo
            image: busybox
            command:
              - sh
              - -c
              - >
                echo "backup started" ;
                mkdir -p /backup &&
                mkdir -p /data &&
                cp -r /data /backup &&
                echo "backup complete" ;
            volumeMounts:
              - name: data-volume
                mountPath : /data
              - name: backup-volume
                mountPath: /backup
        restartPolicy: OnFailure       
        volumes:
        - name:  data-volume
          hostPath:
            path: /data
            type: DirectoryOrCreate
        - name: backup-volume
          hostPath:
            path: /backup
            type: DirectoryOrCreate

