kind: Pod
apiVersion: v1
metadata:
  name: init-pod
  namespace: nginx
spec:
  initContainers:
    - name: init-container
      image: busybox:latest
      command: ["sh","-c","echo 'initialization' && sleep 10"]
  containers:
   - name: main-container
     image: busybox:latest
     command: ["sh","-c","echo 'initialization completed' && sleep 10"]
