kind: PersistentVolume
apiVersion: v1
metadata:
  name: pv
  namespace: nginx
  labels:
    app: nginx
spec:
  capacity:
    storage: 1Gi
  accessModes:
   - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  hostPath:
    path: /mnt/pvdata
      
