kind: Deployment
apiVersion: apps/v1
metadata:
  name: deployement-hpa
  namespace: apache
spec:
  replicas: 2
  selector:
    matchLabels:
     app: apache-app
  template:
    metadata:
      name: hpa-pod
      labels:
        app: apache-app

    spec:
      containers:
        - name: hpa-container
          image: httpd:latest
          ports:
           - containerPort: 80
          resources:
            requests:
              cpu: 100m
              memory: 120Mi
            limits:
              cpu: 200m
              memory: 256Mi
